import type { Metadata } from "next";
import { LegalPage } from "@/components/sections/legal-page";

export const metadata: Metadata = {
  title: "Disclaimer",
  description: "Green Flagged is informational and not a substitute for legal advice.",
};

export default function DisclaimerPage() {
  return (
    <LegalPage title="Disclaimer" updated="May 2026">
      <p>
        <strong className="text-text-primary">Not legal advice.</strong>{" "}
        Green Flagged is an informational tool that surfaces risk in
        contracts. It does not provide legal advice. Using Green Flagged does
        not create an attorney-client relationship.
      </p>
      <p>
        Reports are generated by AI models and may contain errors, miss
        context, or apply assumptions that are wrong for your situation. We
        flag low-confidence findings explicitly, but you should always
        sanity-check the verdict against your own reading.
      </p>
      <p>
        For decisions that meaningfully affect you — anything involving
        personal liability, equity, IP transfer to an unfamiliar party, or
        amounts you can&apos;t afford to lose — consult a licensed attorney in
        your jurisdiction.
      </p>
      <p>
        Green Flagged is a strong first read. It is not a replacement for one.
      </p>
    </LegalPage>
  );
}
